# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    target-branch: "main"
    groups:
      i18n:
        patterns:
          - "i18next-parser"
          - "pluralize"
      lint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
          - "prettier"
          - "stylelint"
          - "stylelint-*"
      patternfly:
        patterns:
          - "@patternfly/*"
      test:
        patterns:
          - "@cypress/*"
          - "cypress"
          - "cypress-*"
          - "junit-report-merger"
          - "mocha-junit-reporter"
      types:
        patterns:
          - "@types/*"
    ignore:
      - dependency-name: "react-i18next"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    target-branch: "pattern-fly-5"
    groups:
      i18n:
        patterns:
          - "i18next-parser"
          - "pluralize"
      lint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
          - "prettier"
          - "stylelint"
          - "stylelint-*"
      patternfly:
        patterns:
          - "@patternfly/*"
      test:
        patterns:
          - "@cypress/*"
          - "cypress"
          - "cypress-*"
          - "junit-report-merger"
          - "mocha-junit-reporter"
      types:
        patterns:
          - "@types/*"
    ignore:
      - dependency-name: "react-i18next"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
